### ISSUE TITLE
Вопросы от Тестировщиков к Программистам (Вниманию Вани, Максима и Миши)

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#10]
Тема для обсуждения вопросов между Тестировщиками и Программистами

**Comment by denisstasyev** [comment]
как будет осуществлено соединение машины Админа и пользовательских ПК (через локальную сеть, Интернет или каким способом)? Этот вопрос ключевым образом повлияет на объект тестирования и тестовую среду. Поэтому мы не можем её определить и возникают вопросы с написанием тестов. И ещё один вопрос связан с отсутствием/наличием GUI.

**Comment by denisstasyev** [comment]
Всё уточнено)
