### ISSUE TITLE
Вопросы от Тестировщиков к Аналитику (Вниманию Ромы)

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#11]
Тема для обсуждения вопросов между Тестировщиками и Аналитиком

**Comment by denisstasyev** [comment]
Из требований непонятно, что должна отображать программа, максимальное количество ПК-ведомых, как должна работать программа в случае неожиданного обрыва связи с каким либо ПК?

**Comment by denisstasyev** [comment]
всё уточнено)
