### ISSUE TITLE
Для Тестировщиков (Денис и Юра)

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#13]
В issues теперь есть две темы, в которых вы можете располагать свои вопросы - так что налетайте.
Чем быстрее вы разместите там список своих вопросов - тем лучше, так что пожалуйста, `выложите вопросы до вечера Пятницы`

Кроме того, появилась первая практическая задача - у Программистов проблема с сетью, а именно что-то с портами Роутера (пока такие гипотезы). Спросите, нужна ли им помощь - сейчас этим занимаются Рома и Максим - заодно при личной встрече сможете дополнительно уточнить интересующие вас вопросы. Вопросы про помощь с сетью советую задавать в ВК - так будет быстрее.

Задание с написанием документации остаётся тем же, после уточнения всех вопросов напишите план согласно тому образцу, который он скидывал. Пожалуйста, `скиньте мне этот план не позже вечера Субботы.` Отдельные моменты по распределению пунктов обсудите между собой, я же уже предложил такой расклад - Денис 1 и 2 пунты, Юра 3 и 5 пункты, а 5 пункт - пополам.

**Comment by denisstasyev** [comment]
А почему на следующей недели нельзя?
Почему именно до вечера субботы?

**Comment by GRISHNOV** [comment]
В смысле на буднях? Если не успеваете - то можно сдвинуть

**Comment by denisstasyev** [comment]
Илья, смотри ВК, кинул документ, дальше юрина часть
