### ISSUE TITLE
Проектирование Архитектуры (Обсуждение для всех программистов)

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#2]
**_Обсуждение производим прямо тут - в комментариях_**

1. Давайте определимся со схемой передачи данных между машинами.

Нам говорили про Winsock. Реализовывать через них, или через что-то другое - на ваше усмотрение.
В любом случае прочитайте хотя-бы первые 3 пункта тут:
 https://msdn.microsoft.com/ru-ru/library/dd335942.aspx 

 Какие варианты вижу я:

A - компьютер администратора
B - компьютер клиента
T - период обновления данных

- На компьютере A раз в T секунд выполняется запрос к B на получение данных, на B постоянно слушается порт приёма
- На компьютере B постоянно слушается порт приёма настроек, на машине A есть порт для отправки настроек

Можно сделать наоборот
Определитесь между TCP и UDP - что лучше

`Если есть идеи/замечания - пишите`

`Этот пост будет допиливаться в реальном времени`

В папке DOC есть схема с прошлого занятия

**Comment by Highoc** [comment]
Просто вы понимаете что если пользоваться схемой:

- На компьютере A раз в T секунд выполняется запрос к B на получение данных, на B постоянно слушается порт приёма.

То с периодом T = 0.5 сек за время работы программы 10 минут по сети будет передано 3600 * 10 * 2* 2 = 144 000 запросов (минимум в обе стороны на один!!! компьютер). Пользуясь схемой с подпиской потребуется всего лишь 1 + 3600 * 10 * 2 + 1 = 72 002 запроса (в  два раза меньше!!! мин в обе стороны).
А если оценить в случае 1 за 10 минут от А к В пойдет по ( два запроса в секунду * N машин, если масштабировать ), а в случае 2 всего лишь ( 2*N за 10 минут ), т.е. в 10 * 3600 раз эффективнее (и еще будет линейно расти со временем эффективность). 
С вопросом масштабирования, если надо будет поддерживать несколько Утилит управления, то, очевидно, что гораздо эффективнее будет реализовать именно схему подписчика и издателя (тогда даже ничего переписывать не надо будет).
Я пока не вижу ни одного плюса реализации 1. Жду конструктивных доказательств моего заблуждения.

Насчет Winsoc. Вы готовы писать на .NET? Я считаю, что лучше найти какую-нибудь С/С++ библиотеку.

**Comment by GRISHNOV** [comment]
Схему выше предложил чисто ради примера - еще в прошлый раз говорили, что она не шипко оптимальна. По поводу .NET - согласен, проще с библиотеками. Какие есть предложения?

**Comment by GRISHNOV** [comment]
Большинство вопросов к 29.03.2017 были решены в офлайне
