### ISSUE TITLE
Обсуждение для всех Программистов (Миша,Ваня и Максим)

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#3]
Программистам нужно обсудить и решить следующие вопросы:

1. Среди вас троих нужно выделить Ведущего Программиста, дабы он мог разрешать локальные вопросы по написанию кода и консультировать остальных Программистов. Выберите кого-то.

2. Нужно выбрать единую IDE (в нашем случае Microsoft VS). То есть студия должна у всех быть выпуском от одного года, например, 2015-ого.

3. Студию нужно настроить должным образом, все инструкции по настройке нам рассылали по ящикам вместе с первой презентацией. Если есть вопросы по настройке - пишите мне, чтобы я спросил у него по почте.

4. Нужно определиться со всеми необходимыми библиотеками - это задача для Ведущего Программиста. Пока можно только те, которые нужны для начала.

5. Подумайте, с чего лучше начать писать программу (с какого блока начать).

`Если нет готовых и очевидных мыслей по 4-ому пункту, то отложите его до воскресенья, так как до вечера субботы по плану будет доделана точная схема архитектуры.
Пункт 5 - аналогично.`

**Пожалуйста, дайте мне ответы по всем пунктам до 6 вечера грядущего воскресенья.**
`Просьба - все обсуждения проводите прямо тут.`

**Comment by GRISHNOV** [comment]
Ведущим Программистом назначается...Максим

**Comment by Highoc** [comment]
А может все таки в демократию?)

**Comment by GRISHNOV** [comment]
Ну можно, конечно, проголосовать) Давайте, кто за кого?

**Comment by GRISHNOV** [comment]
Вопросы обсуждены и частично закрыты на совместном собрании.
