### ISSUE TITLE
Максим

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#4]
Нужно сделать пояснения к некоторым пунктам на фото нашей архитектуры (фото с урока можешь найти в папке DOC), а именно:

1. Опиши базу данных на машине админа:
a) Какая информация храниться о каждом клиенте (IP, port, .......)
б) Каким образом происходит заполнение базы данных, как происходит её обновление (добавление новых, удаление старых) - через консоль или вручную в config?
в) Нам говорили, что базу и config на машине Администратора логично слить в один файл - тогда подумай о формате и структуре конечного файла "база+config".
г) Что будет с базой, если компьютер Администратора внезапно выключится - сохранится ли она? Да и вообще, сохраняются ли настройки прошлой сессии при завершении работы?

2. Детально опиши процесс подключения новых клиентов, и удаление старых (работа по сети):
a) Утилита посылает subscr() на Агента, и агент должен ответить(смотри схему с урока) => опиши аргуметы и механизм subscr(). Что именно должен ответить Агент (на схеме есть обратная стрелочка под стрелочкой с subscr(). ) ?
б) Аналогично распиши для unsubscr(), нужно ли агенту отвечать на него?  
в) Что входит в data? Нужно ли отвечать чем-либо на это со стороны Утилиты (например, какое-то подтверждение), или с data поток односторонний (с Агента на Утилиту)?
г) Под каким видом передаётся data? (формат данных) 
д) Что будет, если комп Админа упадёт? Произойдёт ли автоматический  unsubscr()? А если упадёт сеть или отдельный Агент? То есть рассмотри подобные внештатные ситуации.
е) Опиши функциональные блоки для Утилиты и Агента.(То самое, что внутри прямоугольников) (Например: WinAPI,DATA,Consol,Log,NET .....)
ж) Дай подробное описание всем функциональным блокам, обозначенным в пункте (е).

3. Журналирование (Пока можно не трогать)
а) Каким образом можно скидывать логи с Клиентов на Утилиту, где и как эти логи будут храниться, будут ли они сохраняться после выключения компьютера?
б) Каким потоком можно это реализовать, или вклинить в поток data?
в) Нужен ли отдельный функциональный блок в Утилите под эту задачу?

Я мог что-то забыть. Если это так - допиши то, что посчитаешь важным / нужным / требующим уточнения.

**В ходе работы не забывай использовать предшествующие наработки (смотри ЧУСИК в DOC )**

`Подумай, какие библиотеки нужны, чтобы всё это закодить, а также с чего лучше начать.
Какие-то пункты можешь кинуть Ване (не Мише, он отсутствовал, ему я поручу что-то другое).`
`Если надумаешь кинуть Ване часть вопросов - договаривайся с ним лично.`
*Но вообще, для целостности картины, пожалуйста, распиши всё лично.*

`Не забудь заглянуть в общее обсуждение для Программистов - там есть вопросы, которые вы должны решить совместно.`

**Прошу скинуть мне результаты до 6 вечера грядущей субботы.**

**Comment by Highoc** [comment]
0) Предлагаю сделать отдельную папку в master для презентаций. Ибо когда много всего неудобно что либо смотреть и искать.

1) Сетевое "соединение" предлагаю реализовывать с помощью библиотеки ZeroMQ (поддерживает С++). [https://habrahabr.ru/post/198578/] -  вольный перевод книги о ZeroMQ.

a) Информация о каждом клиенте на данном этапе будет храниться в виде xml структуры в отдельном файле (потом, возможно, в БД). Наиболее вероятный пример структуры:
```
<agents>
   <agent>
      <id> ... </id>
      <name> ... </name>
      <state> active/wait/passive </state> //состояние Агента - посылает/ожидает/не посылает
      <ip> ... </ip>
      <port> ... </port>
      <params>
         <waitT> ... </waitT> //время рассылки Агентом сообщений
         ...  //фильтр рассылки
      </params>
   </agent>
   ...
</agents>
```
б) Заполнение этого файла (далее буду называть его БД) осуществляется как и через "ручками" в файле БД (на этапе отладки), так и с помощью интерфейса командной строки Утилиты с помощью соответствующих функций [-добавить/удалить Агента].

в) Смотри п.1.а). Но скорее это будет не слияние БД с config-файлами. На машине с Утилитой будет свой config-файл, а котором будет иная информация (не БД).

г) В случае выключения компьютера Утилиты во время записи в БД - без механизма транзакций ничья целостность не гарантируется; в случае выключения Утилиты "нормальным" способом все active-агенты переходят в режим wait, для соответствующих Агентов вызывается функция [-отписаться]. При включении Утилиты снова для всех wait-агентов вызывается функция [-подписаться] со всеми параметрами, указанными в БД (механизм сессий).

**Comment by Highoc** [comment]
2. Процесс работы работы с Агентами

   я) Подключение новых и удаление старых осуществляется функциями [-добавить/удалить Агента] (1.б)).

   a) Для "активации" Агента требуется для неактивного Агента вызвать [-подписаться] с соответствующими настройками периода, фильтра и т.д., на что Агент вернет Утилите "код возврата" (успешное подключение / ...).

   б) Для "деактивации" Агента требуется для активного Агента вызвать [-отписаться], Агент ничего не возвращает.

   в-г) Data - xml-сериализованные Данные, ответ Утилиты Агенту не предусмотрен.

   д) см. пункт 1.г) + если упадет Агент, то, возможно, по отсутствию входных данных от него Утилита должна понимать, что Агент "сломан", и реагировать на это (на первых этапах не предусмотрено). 

   е) У Агента блоки: net - работа с сетью, data - работа с win.api (+ logs + config), logic - связующие компоненты. У Утилиты: net - работа с сетью, data - работа с  БД (+ logs + config), logic - связующие компоненты, console/gui - внешний пользовательский интерфейс.

  ж) Это было нами обсуждено в прошлый сбор. Голосую за то что бы снова его провести и обсудить с чего лучше начать. А еще есть вопросы, которые мы должны решить совместно.

**Comment by Highoc** [comment]
3. Журналирование
  Журналирование будет вестись на каждой машине отдельно за время указанное в config файле. При  вызове [-просмотретьЛог] с соответствующими настроками ... (не актуально до появления gui).
