### ISSUE TITLE
Первичное распределение задач по написанию кода

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#7]
**Ваня** - `Process`
Узнай механизмы считывания показателей потребления ресурсов у процессов в Windows.
Посмотри на принципы работы WinAPI.
Помимо этого, если будешь успевать к среде, набросай какой-то код, хотя бы в виде заготовки на будущее.

`Если нужна консультация по каким-то техническим вопросам - обращайся к Максиму.`

**Миша** - `GUI`
GUI - Графический Интерфейс Пользователя <=> Окошко с кнопочками для программы.
Почитай в интернете, как вообще работает графический интерфейс и посредством чего его реализовывают в Windows.
Начни разбираться в WinAPI - начать можно с того же MSDN.
При возможности сделай какие-то наброски кода, хотя бы на будущее.
Не забудь настроить студию и скачать Git.

`Если нужна консультация по каким-то техническим вопросам - обращайся к Максиму.`

**Рома** - `NET`
Изучи, как можно установить связь между компьютерами в локальной сети с помощью ZeroMQ.
На Хабре есть русскоязычный перевод по этой библиотеке (Максим указывал ссылку в своей работе).

`Если нужна консультация по каким-то техническим вопросам - обращайся к Максиму.`

**Максим** - `Всего понемногу`
Будет неплохо посмотреть на WinAPI.
И главное подсказать остальным, если у них возникнут вопросы.

**Общие задачи остаются - пожалуйста, подкрутите настройки в своих студиях (договорились, что пользуемся 2015 версией) , а также скачайте git**
`(Настройки студии нам высылали в письме с самой первой лекцией)`

**Comment by BAHEK98** [comment]
#include <Windows.h>
#include <stdio.h>
#include <stdlib.h>

int main()
{
	MEMORYSTATUSEX s;
	s.dwLength = sizeof(s);
	GlobalMemoryStatusEx(&s);
	printf("%li%%\t%llfMB", s.dwMemoryLoad, s.ullTotalPhys / 1048576.0);
	system("pause");
	return 0;
}


https://msdn.microsoft.com/en-us/library/aa366589(v=vs.85).aspx

остальные функции там тоже можно найти, если надо

**Comment by nilune** [comment]
Собственно если кому интересно - выводит список запущенных процессов на вашем компьютере(если убрать комментария, то и подпроцессы)

#include <windows.h>
#include <tlhelp32.h>

VOID PrintModuleList(HANDLE CONST hStdOut, DWORD CONST dwProcessId) {
	MODULEENTRY32 meModuleEntry;
	TCHAR szBuff[1024];
	DWORD dwTemp;
	HANDLE CONST hSnapshot = CreateToolhelp32Snapshot(
		TH32CS_SNAPMODULE, dwProcessId);
	if (INVALID_HANDLE_VALUE == hSnapshot) {
		return;
	}
	meModuleEntry.dwSize = sizeof(MODULEENTRY32);
	Module32First(hSnapshot, &meModuleEntry);
	do {
		wsprintf(szBuff, L"  ba: %08X, bs: %08X, %s\r\n",
			meModuleEntry.modBaseAddr, meModuleEntry.modBaseSize,
			meModuleEntry.szModule);
		WriteConsole(hStdOut, szBuff, lstrlen(szBuff), &dwTemp, NULL);
	} while (Module32Next(hSnapshot, &meModuleEntry));
	CloseHandle(hSnapshot);
}

VOID PrintProcessList(HANDLE CONST hStdOut) {
	PROCESSENTRY32 peProcessEntry;
	TCHAR szBuff[1024];
	DWORD dwTemp;
	HANDLE CONST hSnapshot = CreateToolhelp32Snapshot(
		TH32CS_SNAPPROCESS, 0);
	if (INVALID_HANDLE_VALUE == hSnapshot) {
		return;
	}
	peProcessEntry.dwSize = sizeof(PROCESSENTRY32);
	Process32First(hSnapshot, &peProcessEntry);
	do {
		/*wsprintf(szBuff, L"=== %08X %s ===\r\n",
			peProcessEntry.th32ProcessID, peProcessEntry.szExeFile);*/
		wsprintf(szBuff, L"%s ===\r\n",
			peProcessEntry.szExeFile);
		WriteConsole(hStdOut, szBuff, lstrlen(szBuff), &dwTemp, NULL);
		//PrintModuleList(hStdOut, peProcessEntry.th32ProcessID);
	} while (Process32Next(hSnapshot, &peProcessEntry));
	CloseHandle(hSnapshot);
}

INT main() {
	HANDLE CONST hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
	PrintProcessList(hStdOut);
	system("pause");
	ExitProcess(0);
}

**Comment by Highoc** [comment]
ZeroMQ протестена, соединение устанавливает, все друг другу пересылает, хоть и нужны некоторые предварительные танцы с бубном (http://stackoverflow.com/questions/27737155/setting-up-zeromq-in-a-visual-studio-13-project). Предлагаю собраться вновь, распределить реальные задания и продолжить. 
А если вы зайдете на ссылку, которую я прилагал в архитектуре, то будете приятно удивлены. Во второй главе разбирается именно наша модель издателя-подписчика с настоящим примером, фильтрацией и прочим.

**Comment by GRISHNOV** [comment]
Предлагаю собраться завтра, перед двумя парами информатики, в районе 15:30 - 16:55
