### ISSUE TITLE
Денис и Юра

### ISSUE THREAD

**Issue by GRISHNOV** [GRISHNOV/Remote-Performance-Monitoring-KB_619_Project#9]
Нужно составить документ (План Тестирования) по образцу, который я переслал вам на почту
Для справки смотрите слайды с последнего занятия (все лекции есть в DOC)
Предлагаю следующее распределение:
- Первый и второй пункты - для Дениса, четвёртый и пятый - Юра, а третий поделите пополам (либо договоритесь кому он достанется)

`В качестве опоры используйте оба файла от Ромы (Архитектура + Требования к ПО). Всё что вы пишете обязательно должно опираться на эти документы.`

Если возникают вопросы - задавайте либо Роме, либо мне (в особенности вопросы, связанные с документами по Требованиям и Архитектуре)

**Comment by denisstasev** [comment]
Мы всё вместе пилим, но на завтра не успеем

**Comment by denisstasyev** [comment]
На завтра мы не успеваем (всё вместе делаем, чтобы был единый план), так как поздно Рома требования доделал.

**Comment by denisstasyev** [comment]
Также есть фундаментальный вопрос к программистам, как будет осуществлено соединение машины Админа и пользовательских ПК (через локальную сеть, Интернет или каким способом)? Этот вопрос ключевым образом повлияет на объект тестирования и тестовую среду. Поэтому мы не можем её определить и возникают вопросы с написанием тестов. И ещё один вопрос связан с отсутствием/наличием GUI. Поговори с программистами, пусть они определят точнее эти моменты и напиши, что решите, пожалуйста.

**Comment by denisstasyev** [comment]
Просто сложно писать тесты без понимания хотя бы пользовательской стороны дела

**Comment by denisstasyev** [comment]
Илья, а Юра тут есть, а то у меня только 2 участника показывает?

**Comment by denisstasyev** [comment]
И вопрос к Роме, из требований непонятно, что должна отображать программа, максимальное количество ПК-ведомых, как должна работать программа в случае неожиданного обрыва связи с каким либо ПК. Это важно. Не хватает конкретики, без этого мы мало чего протестируем
